# Generated by Django 5.2 on 2025-04-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='record_lap_time',
        ),
        migrations.AddField(
            model_name='circuit',
            name='record_lap_info',
            field=models.CharField(blank=True, default='', help_text='e.g. 1:27.097 - Max Verstappen (2020, Red Bull)', max_length=200, verbose_name='Record Lap Info'),
        ),
    ]
