# Generated by Django 5.2 on 2025-04-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0002_remove_circuit_record_lap_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='circuit_length',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Length of one lap, in kilometers', max_digits=5, null=True, verbose_name='Circuit Length (km)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='first_grand_prix',
            field=models.IntegerField(blank=True, help_text='The year of the first Grand Prix held here', null=True, verbose_name='First Grand Prix Year'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='number_of_laps',
            field=models.IntegerField(blank=True, help_text='Total laps in a full race here', null=True, verbose_name='Number of Laps'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='race_distance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total race distance, in kilometers', max_digits=6, null=True, verbose_name='Race Distance (km)'),
        ),
    ]
