# Generated by Django 5.2 on 2025-04-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0004_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='continent',
            field=models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania'), ('AN', 'Antarctica')], default='EU', help_text='Continent where the circuit is located', max_length=2),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='record_lap_info',
            field=models.CharField(blank=True, default='', help_text='e.g. 1:27.097 – Max Verstappen (2020, Red Bull)', max_length=200, verbose_name='Record Lap Info'),
        ),
    ]
