# Generated by Django 5.2 on 2025-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0005_circuit_continent_alter_circuit_record_lap_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='introduction',
            field=models.TextField(blank=True, default='', help_text='A brief intro or overview of this circuit', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='fun_fact',
            field=models.TextField(help_text='Interesting fact about the circuit', verbose_name='Fun fact'),
        ),
    ]
