# Generated by Django 3.2.25 on 2025-05-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0006_circuit_introduction_alter_circuit_fun_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='most_wins_count',
            field=models.IntegerField(blank=True, help_text='Number of wins for the driver with the most wins.', null=True, verbose_name='Most Wins Count'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='most_wins_driver',
            field=models.CharField(blank=True, help_text='Name of the F1 driver with the most wins at this circuit.', max_length=100, null=True, verbose_name='Most Wins Driver'),
        ),
    ]
