# Generated by Django 3.2.25 on 2025-05-01 16:21

import circuits.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circuits', '0007_auto_20250501_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(choices=[('Mercedes W15', 'Mercedes W15'), ('Red Bull RB20', 'Red Bull RB20'), ('Ferrari SF-24', 'Ferrari SF-24'), ('McLaren MCL38', 'McLaren MCL38'), ('Aston Martin AMR24', 'Aston Martin AMR24'), ('Alpine A524', 'Alpine A524'), ('Williams FW46', 'Williams FW46'), ('RB VCARB 01', 'RB VCARB 01'), ('Kick Sauber C44', 'Kick Sauber C44'), ('Haas VF-24', 'Haas VF-24')], max_length=50)),
                ('lap_time', models.CharField(help_text='Enter lap time in MM:SS.mmm or SS.mmm format (e.g., 1:23.456 or 83.456)', max_length=15, validators=[circuits.models.validate_lap_time_format])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='circuits.circuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lap_time'],
                'unique_together': {('circuit', 'user', 'car')},
            },
        ),
    ]
