# Generated by Django 5.1.6 on 2025-02-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.CharField(max_length=50),
        ),
    ]
